# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2021-02-26 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0003_expand_course_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peerworkflow',
            name='item_id',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='staffworkflow',
            name='item_id',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='studenttrainingworkflow',
            name='item_id',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
